# Generated by Django 4.0.3 on 2022-03-25 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='template',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='template',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='template',
            name='body_uz',
        ),
        migrations.AddField(
            model_name='template',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
