# Generated by Django 4.0.3 on 2022-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_hotel_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='backend/hotels', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг(из 10)'),
        ),
    ]
