# Generated by Django 4.0.3 on 2022-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_date_from_booking_date_remove_booking_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
